import { docs } from "collections/server";
import { loader } from "fumadocs-core/source";

// The headless content source. `docs` is the collection generated by fumadocs-mdx
// from content/docs (.source/server.ts); loader() turns it into a page tree +
// slug lookup rooted at /docs. We render everything with our own UI — no
// fumadocs-ui — so this is the only fumadocs surface the app depends on.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
