import { docs } from "collections/server";
import { loader } from "fumadocs-core/source";
import { i18n } from "@/lib/i18n";

// The headless content source. `docs` is the collection generated by fumadocs-mdx
// from content/docs (.source/server.ts); loader() turns it into a page tree +
// slug lookup rooted at /docs. We render everything with our own UI — no
// fumadocs-ui — so this is the only fumadocs surface the app depends on.
//
// With `i18n` wired in, a page is looked up as (slug, language): the loader reads
// `<page>.<locale>.mdx` beside the English source and falls back to English for
// anything not translated yet.
export const source = loader({
  baseUrl: "/docs",
  i18n,
  source: docs.toFumadocsSource(),
});
